# Generated by Django 4.2.6 on 2023-10-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date_of_registration', models.DateField()),
                ('company_registration_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('number_of_employees', models.IntegerField()),
                ('contact_phone', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
