# Generated by Django 4.2.6 on 2023-10-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentVerify', '0002_role_alter_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_left',
            field=models.DateField(null=True),
        ),
    ]
