# Generated by Django 4.2.6 on 2023-10-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talentVerify', '0002_delete_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('date_started', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('date_left', models.DateField(null=True)),
                ('role_duty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentVerify.role_duties')),
            ],
        ),
    ]
